/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ApplicationRecords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApplicationRecordDto"][];
                        "application/json": components["schemas"]["ApplicationRecordDto"][];
                        "text/json": components["schemas"]["ApplicationRecordDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateApplicationRecordRequest"];
                    "text/json": components["schemas"]["CreateApplicationRecordRequest"];
                    "application/*+json": components["schemas"]["CreateApplicationRecordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApplicationRecordDto"];
                        "application/json": components["schemas"]["ApplicationRecordDto"];
                        "text/json": components["schemas"]["ApplicationRecordDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ApplicationRecords/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApplicationRecordDto"];
                        "application/json": components["schemas"]["ApplicationRecordDto"];
                        "text/json": components["schemas"]["ApplicationRecordDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateApplicationRecordRequest"];
                    "text/json": components["schemas"]["UpdateApplicationRecordRequest"];
                    "application/*+json": components["schemas"]["UpdateApplicationRecordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApplicationRecordDto"];
                        "application/json": components["schemas"]["ApplicationRecordDto"];
                        "text/json": components["schemas"]["ApplicationRecordDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ApplicationRecords/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExcelImportResultDto"];
                        "application/json": components["schemas"]["ExcelImportResultDto"];
                        "text/json": components["schemas"]["ExcelImportResultDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApplicationRecordDto: {
            /** Format: int32 */
            id?: number | string;
            companyName?: string;
            status?: components["schemas"]["ApplicationStatus"];
            /** Format: date-time */
            appliedDate?: null | string;
            postingUrl?: null | string;
            notes?: null | string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastModified?: string;
        };
        ApplicationStatus: number;
        CreateApplicationRecordRequest: {
            companyName: string;
            status?: components["schemas"]["ApplicationStatus"];
            /** Format: date-time */
            appliedDate?: null | string;
            postingUrl?: null | string;
            notes?: null | string;
        };
        ExcelImportErrorDto: {
            /** Format: int32 */
            rowNumber?: number | string;
            companyName?: null | string;
            errorMessage?: string;
        };
        ExcelImportResultDto: {
            /** Format: int32 */
            totalRows?: number | string;
            /** Format: int32 */
            importedCount?: number | string;
            /** Format: int32 */
            failedCount?: number | string;
            errors?: components["schemas"]["ExcelImportErrorDto"][];
        };
        /** Format: binary */
        IFormFile: string;
        UpdateApplicationRecordRequest: {
            companyName: string;
            status?: components["schemas"]["ApplicationStatus"];
            /** Format: date-time */
            appliedDate?: null | string;
            postingUrl?: null | string;
            notes?: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
